feat: autocomplete products and hook autocomplete
mouradaniel/std pull request #5
Opened 2023-07-07 22:15 UTC by mouradaniel

2023-07-08 22:01 UTC, gustavo-vasconcellos requested changes

2023-07-08 22:01 UTC, gustavo-vasconcellos commented on loaders/linxImpulse/autocompletes/products.ts
> +export { default } from "../../../packs/linxImpulse/loaders/autocompletes/products.ts";
@mouradaniel Olha os demais loaders e faz a importaçao igual usando `deco-sites/std`

2023-07-08 22:01 UTC, gustavo-vasconcellos commented on packs/linxImpulse/loaders/autocompletes/products.ts
> +import type { ProductLinxImpulse } from "../../types.ts";
Importaçao com `deco-sites/std`

2023-07-08 22:01 UTC, gustavo-vasconcellos commented on packs/linxImpulse/hooks/useAutocomplete.ts
> +    const productsData = await products({ query: search }) as Product[];
Alem de enviar o texto de busca para a funçao coloca para mandar tambem a quantidade de resultados, na API sao esses campos:
![image](https://github.com/mouradaniel/std/assets/29849615/96bedf74-352f-4b97-a1d0-3b7cf4441b24)

2023-07-10 23:40 UTC, mouradaniel commented
@gustavo-vasconcellos 

- Corrigi os imports;
- Mudei a chamada do autocompletes/product para autocompletes;
- Tratei o retorno das queries e ajustei o tipo de retorno para ser uma Suggestion (products e searches);
- Ajustei para receber o count dos termos e produtos;
- Mudei o nome de algumas coisas (products -> suggestions, suggestions -> popular);

Pode revalidar? 
Estou subindo a hash do commit na branch feat/autocomplete, dentro do xpto

2023-07-11 18:52 UTC, gustavo-vasconcellos approved these changes

2023-07-21 23:09 UTC, merged